### PR TITLE
Refactor CSS to SCSS

### LINKED ISSUE #44: CSS refactors
Currently the CSS is one big 1000-line file. It is now unwieldy, and need refactoring.

Possible refactors:

- Split into files for each component
- CSS-in-JS - might be worth putting CSS in same file as component it is for here
- (SCSS?)

Decided to use SASS.

### LINKED ISSUE #62: R-Tab overlaps 'next week' text on mobile
Device: Xiaomi Redmi Note 4X (1080 x 1920)
OS: Android 9.0/LineageOS 16.0
Browser: Chrome Mobile. 

Also occurs in Firefox on Windows 10 when window is made smaller in both x and y directions. I haven't tried with any other browsers.

When the banner alert is closed, the `r-tab`s at the top overlap with `h2.mobile`. 
I think that removing the `position: absolute` from `div.r-tab-row` would fix this issue.

### PR DESCRIPTION
**Pull request by Gum-Joe**
Refactor CSS to SCSS so it is more manageable.
Fixes #44.

TODO:

- [x] Also Fix #62

### CODE REVIEW

**Comment by Gum-Joe** [comment]
(BTW the REPL.IT user is me)

**Comment by Gum-Joe** [comment]
Got to line 490

**Comment by Gum-Joe** [comment]
Got to line 553

**Comment by Gum-Joe** [comment]
Only thing outstanding is #60

**Review by ILikeTeaALot — APPROVED** [review]
other than typos (which can either be fixed with a further commit, or in some future commit to another branch), all looks good 👍

**Pull request merged**
