### PR TITLE
Add notifications banner system

### PR DESCRIPTION
**Pull request by ILikeTeaALot**
completes #19

### CODE REVIEW

**Comment by ILikeTeaALot** [comment]
the correct branch is set so this is good to merge once reviewed

**Comment by Gum-Joe** [comment]
SITE CHECKLIST BEFORE DEPLOY:
1. Ensure everything for v1 is merged into this PR
2. Update events list for BOTH KECHB and KECHG as needed (KECHG needs a new list)
3. Remove alaerts, or set the alert to something that makes sense
4. Ensure site works both with and without cookies
5. Validate the isitweeka text is good and all button work
6. Validate site works both with and without cookies

**Review by Gum-Joe — APPROVED** [review]
APPROVED!

**Comment by ILikeTeaALot** [comment]
it has been done

**Pull request merged**
